### ISSUE TITLE
Performance and compatibility

### ISSUE THREAD

**Issue by deism** [yester31/Real_ESRGAN_TRT#1]
@yester31  Good job!

what video card do you use in your test environment, and how about performance, are all models supported? 

Thanks!

**Comment by yester31** [comment]
@deism hello

You can check environment and performance below link.

* Developmenat Environment
https://github.com/yester31/TensorRT_EX#enviroments

* Performance Evaluation
https://github.com/yester31/TensorRT_EX#super-resolution-model

I made only realesrgan-x4plus model.

**Comment by deism** [comment]
Thanks for the information.
