### ISSUE TITLE
Help ! about image size

### ISSUE THREAD

**Issue by xpo0a** [yester31/Real_ESRGAN_TRT#2]
Thanks for your Enlightening job with Real-ESRGAN.

I can build engine and infer _OST_009.png (the size is 448x640).

However, for other size, such as 179 x179, the infer output is really Confusing. Sometime encounter Segment fault.

can the image size only be 448x640 ?

have a good day!

**Comment by yester31** [comment]
![image](https://user-images.githubusercontent.com/40158321/172180337-73206d6f-ea0a-42ef-9261-489073541974.png)

change the line 15, 16 and rebuild and regenerate engine file.

**Comment by xpo0a** [comment]
thanks, bro
