### ISSUE TITLE
How to use 2x model for inference？

### ISSUE THREAD

**Issue by Bo396543018** [yester31/Real_ESRGAN_TRT#5]
Thanks for your great work.
We want to use a 2x model for inference, but we need to add a pixelunshuffle operation. We try to add it before preprocessing, but find that the results are not correct. Can you give me some advice?

**Comment by yester31** [comment]
Sorry for the late reply. I'm busy these days.
As far as I know, there is no pixelunshuffle layer in the TensorRT API.
I think you can create the same function using addSlice and addConcatenation, addShuffle API. 
Try making it by referring to the implementation in the image below.
If not, creating a cuda kernel function and making it a plugin layer is one way.

![image](https://user-images.githubusercontent.com/40158321/178153692-161fe6ad-c19e-4033-9335-048dc3abed9e.png)

I hope you have already solved it.
If ... if it's hard, ask me again.

**Comment by Bo396543018** [comment]
Hi,Thank you for your replay.
Before you reply, We tried some modifications.
Since we are not very familiar with Tensorrt, we first used C++ to implement the pixelunshuffle operation before preprocessing, and then sent it to the preprocessing function, hoping to get consistent results and subsequent implementation through plugins. but it seems that the results are a bit problematic at present. 
We modify the details as follows:
1) input size
```
static const int INPUT_H = 640;
static const int INPUT_W = 448;
static const int INPUT_C = 12;
static const int OUT_SCALE = 2;
static const int OUTPUT_SIZE = INPUT_C * INPUT_H * OUT_SCALE * INPUT_W * OUT_SCALE;
```
2）add pixelunshuffle operation before preprocess
```
     cv::Mat img = cv::imread(img_dir + "/" + file_names[0]);
        cv::Mat unshuffled_img(cv::Size(INPUT_W, INPUT_H), CV_8UC(12));
        PixelUnshuffle(img, unshuffled_img, 2);
        
        if (img.empty()) continue;
        memcpy(input.data() + b * INPUT_H * INPUT_W * INPUT_C, unshuffled_img.data, INPUT_H * INPUT_W * INPUT_C);
    void PixelUnshuffle(cv::Mat &img, cv::Mat &output, int r) {
    
        // cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
        int img_w = img.cols; 
        int img_h = img.rows; 
        int channels = img.channels();
        for (int c = 0; c < channels; c++ ){
            for (int w = 0; w < img_w; w++) {
                for (int h = 0; h < img_h; h++ ) {
    
                    int new_h = int(h / r);
                    int new_w = int(w / r);
                    int new_c = c * r * r + (h % r) * r + (w % r);
    
                    float img_pixel = float(img.at<cv::Vec3b>(h, w)[c]);
                    output.at<cv::Vec3b>(new_h, new_w)[new_c] = img_pixel;
                }
            }
        }
    }
```

3）Modify RGB conversion in preprocessing
```
__global__ void preprocess_kernel(float* output, uint8_t* input,
    const int batchSize, const int height, const int width, const int channel,
    const int thread_count)
{
    int index = threadIdx.x + blockIdx.x * blockDim.x;
    if (index >= thread_count) return;
    const int w_idx = index % width;
    int idx = index / width;
    const int h_idx = idx % height;
    idx /= height;
    const int c_idx = idx % channel;
    const int b_idx = idx / channel;

    int g_idx = b_idx * height * width * channel + h_idx * width * channel + w_idx * channel + 11 - c_idx;

    output[index] = input[g_idx] / 255.f;
}
```
We think this can align the input of the model, but we get the wrong result as shown in the figure below, where can we possibly have a problem? 
![_OST_009](https://user-images.githubusercontent.com/30313569/178313950-f8786c03-f34e-4597-9358-3254d5ba6616.png)

**Comment by yester31** [comment]
Did you change only the front part of the model from real esrgan x4 model? 
if you did that.
Maybe, you should change tensorRT model follow x2 pytorch model.

**Comment by Bo396543018** [comment]
> Did you change only the front part of the model from real esrgan x4 model? if you did that. Maybe, you should change tensorRT model follow x2 pytorch model.

No, I have converted the 2x model to wts.

**Comment by Bo396543018** [comment]
> Did you change only the front part of the model from real esrgan x4 model? if you did that. Maybe, you should change tensorRT model follow x2 pytorch model.

I found a problem, when I tested the 2x code I modified with the pictures provided in the repo, H and W forgot to divide by 2, I will provide the modified results later

**Comment by yester31** [comment]
I'm not sure if you solved the problem, but if you're still struggling, check out the link below
https://github.com/wang-xinyu/tensorrtx/issues/1085#issuecomment-1229422132
