### ISSUE TITLE
Error when creating 16fp engine in windows for large images

### ISSUE THREAD

**Issue by HosseinMoazzam** [yester31/Real_ESRGAN_TRT#8]
## Env

- GPU: GeForce GTX 1660
- OS: Windows 10
- Cuda version: 11.3
- TensorRT version: 8.2.5

## Problem
When creating 16fp engine in windows for large images (such 1220*900), the error shown in the image occurs. In ubuntu, there is no such error. My .wts file is created from realesragan_x2plus model.

![1](https://user-images.githubusercontent.com/73931196/205657022-9bb59a2c-5e19-45a8-bbf8-753082674e03.PNG)

**Comment by tuteming** [comment]
HosseinMoazzam:
Can you give a CMakeLists.txt for win10, thanks
my email:  tuteming@gmail.com

**Comment by HosseinMoazzam** [comment]
> HosseinMoazzam: Can you give a CMakeLists.txt for win10, thanks my email: [tuteming@gmail.com](mailto:tuteming@gmail.com)

I use Visual Studio directly to run the code not CMake.

**Comment by tuteming** [comment]
you GPU: GeForce GTX 1660, that is not tensor core, only run fp32 not fp16.
you can check https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/check_fp16_int8_support.md

**Comment by tuteming** [comment]
I use Visual Studio directly to run the code not CMake.
how to run? thanks

**Comment by HosseinMoazzam** [comment]
> you GPU: GeForce GTX 1660, that is not tensor core, only run fp32 not fp16. you can check https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/check_fp16_int8_support.md

Thanks for your reply. The CUDA arch (compute capability) of my GPU is 7.5 and this can run fp16. Also the code is ran in ubuntu without any problem.

**Comment by HosseinMoazzam** [comment]
> I use Visual Studio directly to run the code not CMake. how to run? thanks

1- Open a new CUDA project in VS
2- Add the paths of include and library directories of TensorRT and OCV to C++ directory, and the name of libraries to the linker, in project properties
3- Add the files of Real-Esrgan to the project
4- Built the project

**Comment by tuteming** [comment]
thanks
